name: xplore
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - matplotlib
  - pip:
    - tensorflow==2.10
    - opencv-python
    - opencv-python-headless
    - tqdm
